spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
    url: jdbc:postgresql://localhost:5432/postgres-service

  application:
    name: payment-service
  liquibase:
    enabled: true
    default-schema: payment_service
    change-log: /db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost