spring:
  application:
    name: account-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres-service}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    properties:
      schema: account_service
  liquibase:
    enabled: true
    default-schema: account_service
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost