spring:
  application:
    name: account-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/account-service}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver